---
name: Bug Report
about: Create a report to help us improve
title: '[BUG] '
labels: ['bug', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you were trying to do and what happened instead.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (blocks core functionality)
        - High (major feature broken)
        - Medium (feature impaired)
        - Low (minor issue)
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment.
      placeholder: 'OS: Windows 11, Node: 18.17.0, pnpm: 8.6.0'
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Screenshots, logs, or other relevant information.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please verify the following
      options:
        - label: I have searched for similar issues and confirmed this is not a duplicate
          required: true
        - label: I have provided clear reproduction steps
          required: true
        - label: I have included relevant environment details
          required: true
