---
name: Documentation Issue
about: Report issues with documentation
title: '[DOCS] '
labels: ['documentation', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What documentation issue did you find?
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: 'README.md, docs/setup.md, etc.'
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: How can we improve this documentation?
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please verify the following
      options:
        - label: I have searched existing documentation issues
          required: true
